package au.com.satech.wds.model;
// Generated 27/04/2011 2:03:13 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer")
public class Answer extends BaseObject implements java.io.Serializable {
     private Integer answerid;
     private String answertitle;
     private Integer answerorder;

    public Answer() {
    }

    public Answer(String answertitle, Integer answerorder) {
       this.answertitle = answertitle;
       this.answerorder = answerorder;
    }
   
@Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="answerid", unique=true, nullable=false)
    public Integer getAnswerid() {
        return this.answerid;
    }
    
    public void setAnswerid(Integer answerid) {
        this.answerid = answerid;
    }
    
    @Column(name="answertitle",nullable=false, length=600)
    public String getAnswertitle() {
        return this.answertitle;
    }
    
    public void setAnswertitle(String answertitle) {
        this.answertitle = answertitle;
    }
    
    @Column(name="answerorder")
    public Integer getAnswerorder() {
        return this.answerorder;
    }
    
    public void setAnswerorder(Integer answerorder) {
        this.answerorder = answerorder;
    }
    
    @Transient
    public boolean isIdSet(){
        if(getAnswerid()==null) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        ToStringBuilder sb = new ToStringBuilder(this, ToStringStyle.DEFAULT_STYLE)
                .append("answer id", this.answerid)
                .append("answer title", this.answertitle)
                .append("answer order",this.answerorder);
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(!(o instanceof Answer)){
            return false;
        }
        final Answer answer = (Answer)o;
        
        return !(answerid != null ? !(answer.getAnswerid() == answerid) : answer.getAnswerid() != null);
    }

    @Override
    public int hashCode() {
        return (answerid != null ? answerid.hashCode() : 0);
    }
    
}


