package au.com.satech.wds.model;
// Generated 27/04/2011 2:03:13 AM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * Subquestion generated by hbm2java
 */
@Entity
@Table(name="subquestion")
public class Subquestion extends BaseObject implements java.io.Serializable {


     private Integer subquestionid;
     private String subquestiontitle;
     private Integer subquestionorder;
     private List<String> responseColumnchoiceIds = new ArrayList<String>();
     private Entry entry = new Entry();
     private Integer selectedStars;
     private Integer scenarioComparator;
     private List<String> SelectedColumnchoices;
     private String randomString;

    public Subquestion() {
    }

    public Subquestion(Question question, String subquestiontitle, Integer subquestionorder) {
       this.subquestiontitle = subquestiontitle;
       this.subquestionorder = subquestionorder;
    }
   
@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="subquestionid", unique=true, nullable=false)
    public Integer getSubquestionid() {
        return this.subquestionid;
    }
    
    public void setSubquestionid(Integer subquestionid) {
        this.subquestionid = subquestionid;
    }
    
    @Transient
    public boolean isIdSet(){
        if(getSubquestionid()==null) {
            return false;
        }
        return true;
    }
    
    @Column(name="subquestiontitle", length=600)
    public String getSubquestiontitle() {
        return this.subquestiontitle;
    }
    
    public void setSubquestiontitle(String subquestiontitle) {
        this.subquestiontitle = subquestiontitle;
    }
    
    @Column(name="subquestionorder")
    public Integer getSubquestionorder() {
        return this.subquestionorder;
    }
    
    public void setSubquestionorder(Integer subquestionorder) {
        this.subquestionorder = subquestionorder;
    }

    @Transient
    public Integer getSelectedStars() {
        return selectedStars;
    }

    public void setSelectedStars(Integer selectedStars) {
        this.selectedStars = selectedStars;
    }

    @Transient
    public Integer getScenarioComparator() {
        return scenarioComparator;
    }

    public void setScenarioComparator(Integer scenarioComparator) {
        this.scenarioComparator = scenarioComparator;
    }

    @Transient
    public List<String> getSelectedColumnchoices() {
        return SelectedColumnchoices;
    }

    public void setSelectedColumnchoices(List<String> SelectedColumnchoices) {
        this.SelectedColumnchoices = SelectedColumnchoices;
    }
    
    

    @Override
    public String toString() {
        ToStringBuilder sb = new ToStringBuilder(this, ToStringStyle.DEFAULT_STYLE)
                .append("sub-question id", this.subquestionid)
                .append("sub-question title", this.subquestiontitle)
                .append("sub-question order",this.subquestionorder);
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(!(o instanceof Subquestion)){
            return false;
        }
        final Subquestion subQuestion = (Subquestion)o;
        
        return !(subquestionid != null ? !(subQuestion.getSubquestionid() == subquestionid) : subQuestion.getSubquestionid() != null);
    }

    @Override
    public int hashCode() {
        return (subquestionid != null ? subquestionid.hashCode() : 0);
    }

    /**
     * @return the entry
     */
    @Transient
    public Entry getEntry() {
        return entry;
    }

    /**
     * @param entry the entry to set
     */
    public void setEntry(Entry entry) {
        this.entry = entry;
    }

    /**
     * @return the responseColumnchoiceIds
     */
    @Transient
    public List<String> getResponseColumnchoiceIds() {
        return responseColumnchoiceIds;
    }

    /**
     * @param responseColumnchoiceIds the responseColumnchoiceIds to set
     */
    public void setResponseColumnchoiceIds(List<String> responseColumnchoiceIds) {
        this.responseColumnchoiceIds = responseColumnchoiceIds;
    }
    @Transient
    public String getRandomString() {
        return randomString;
    }

    public void setRandomString(String randomString) {
        this.randomString = randomString;
    }
    
}


