package au.com.satech.wds.model;
// Generated 27/04/2011 2:03:13 AM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name="survey")
public class Survey extends BaseObject implements java.io.Serializable {
    
     private Integer sid;
     private String surveytitle;
     private String surveydescription;
     private String surveywelcometext;
     private String surveyendtext;
     private String supervisor;
     private String supervisoremail;
     private boolean active;
     private Date expires;
     private String language;
     private boolean usecookie;
     private boolean allowsave;
     private boolean attributedescriptions;
     private Date datecreated;
     private String lockUser;
     private boolean occupy;
     private Set<Page> pages = new HashSet<Page>();
     private List<Page> pageList = new ArrayList<Page>();

    public Survey() {
    }

    public Survey(String surveytitle, String surveydescription, String surveywelcometext, String surveyendtext, String supervisor, String supervisoremail, boolean active, Date expires, String language, boolean usecookie, boolean allowsave, boolean attributedescriptions, Date datecreated, Set<Page> pages, List<Page> pagesList ) {
       this.surveytitle = surveytitle;
       this.surveydescription = surveydescription;
       this.surveywelcometext = surveywelcometext;
       this.surveyendtext = surveyendtext;
       this.supervisor = supervisor;
       this.supervisoremail = supervisoremail;
       this.active = active;
       this.expires = expires;
       this.language = language;
       this.usecookie = usecookie;
       this.allowsave = allowsave;
       this.attributedescriptions = attributedescriptions;
       this.datecreated = datecreated;
       this.pages = pages;
       this.pageList = pagesList;
    }
   
@Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="sid", unique=true, nullable=false)
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    
    @Column(name="surveytitle", length=200)
    public String getSurveytitle() {
        return this.surveytitle;
    }
    
    public void setSurveytitle(String surveytitle) {
        this.surveytitle = surveytitle;
    }
    
    @Column(name="surveydescription", length=650)
    public String getSurveydescription() {
        return this.surveydescription;
    }
    
    public void setSurveydescription(String surveydescription) {
        this.surveydescription = surveydescription;
    }
    
    @Column(name="surveywelcometext", length=400)
    public String getSurveywelcometext() {
        return this.surveywelcometext;
    }
    
    public void setSurveywelcometext(String surveywelcometext) {
        this.surveywelcometext = surveywelcometext;
    }
    
    @Column(name="surveyendtext", length=400)
    public String getSurveyendtext() {
        return this.surveyendtext;
    }
    
    public void setSurveyendtext(String surveyendtext) {
        this.surveyendtext = surveyendtext;
    }
    
    @Column(name="supervisor", length=50)
    public String getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(String supervisor) {
        this.supervisor = supervisor;
    }
    
    @Column(name="supervisoremail", length=320)
    public String getSupervisoremail() {
        return this.supervisoremail;
    }
    
    public void setSupervisoremail(String supervisoremail) {
        this.supervisoremail = supervisoremail;
    }
    
    @Column(name="active")
    public boolean getActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires", length=19)
    public Date getExpires() {
        return this.expires;
    }
    
    public void setExpires(Date expires) {
        this.expires = expires;
    }
    
    @Column(name="language", length=50)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    @Column(name="usecookie")
    public boolean getUsecookie() {
        return this.usecookie;
    }
    
    public void setUsecookie(boolean usecookie) {
        this.usecookie = usecookie;
    }
    
    @Column(name="allowsave")
    public boolean getAllowsave() {
        return this.allowsave;
    }
    
    public void setAllowsave(boolean allowsave) {
        this.allowsave = allowsave;
    }
    
    @Column(name="attributedescriptions")
    public boolean getAttributedescriptions() {
        return this.attributedescriptions;
    }
    
    public void setAttributedescriptions(boolean attributedescriptions) {
        this.attributedescriptions = attributedescriptions;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="datecreated", length=10)
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    
    @Column(name = "lockuser", nullable = true)
    public String getLockUser() {
        return lockUser;
    }

    public void setLockUser(String lockUser) {
        this.lockUser = lockUser;
    }
    public boolean isOccupy() {
        return occupy;
    }

    public void setOccupy(boolean occupy) {
        this.occupy = occupy;
    }
    
@OneToMany(cascade=CascadeType.ALL)
@JoinTable(
            name = "survey_page",
            joinColumns = { @JoinColumn(name = "sid") },
            inverseJoinColumns = @JoinColumn(name = "pageid")
    )
    public Set<Page> getPages() {
        return this.pages;
    }
    
    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }
    
    @Transient
    public List<Page> getPageList() {
        return pageList;
    }

    public void setPageList(List<Page> pageList) {
        this.pageList = pageList;
    }
    

    @Override
    public String toString() {
        ToStringBuilder sb = new ToStringBuilder(this, ToStringStyle.DEFAULT_STYLE)
                .append("survey id", this.sid)
                .append("survey title", this.surveytitle)
                .append("survey description", this.surveydescription);
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Survey)) {
            return false;
        }

        final Survey survey = (Survey) o;

        return !(sid != null ? !(sid == survey.getSid()) : survey.getSid() != null);
    }

    @Override
    public int hashCode() {
        return (sid != null ? sid.hashCode() : 0);
    }
}


